export default{
    state:()=>{
        return{
            isauth:false,
            user:{}
        }
    },
    mutations:{
  getauth(state,payload){
    if(payload)
    state.isauth=payload;

  },
  getuser(state,payload){
    if(payload)
    state.user=payload;
  }
    },
    actions:{
    upgetauth({commit},payload){
        setTimeout(()=>{
            commit('getauth',payload)
        },2000)
    },upgetuser({commit},payload){
        setTimeout(()=>{
            commit('getuser',payload)
        },2000)
    },
    }
  }